openapi: 3.0.0
info:
  title: Gender Healthcare API
  description: API cho dự án Gender Healthcare
  version: 1.0.0
  contact:
    email: admin@genderhealthcare.com

servers:
  - url: /api
    description: API prefix

tags:
  - name: Auth
    description: Xác thực và phân quyền
  - name: User
    description: Quản lý người dùng
  - name: OTP
    description: Quản lý mã OTP và xác thực

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Đăng ký tài khoản mới
      description: Đăng ký tài khoản người dùng mới và gửi email xác thực
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - fullName
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                  minLength: 6
                fullName:
                  type: string
                  minLength: 3
                phone:
                  type: string
      responses:
        '201':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Đăng ký thành công!
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      fullName:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      emailVerified:
                        type: boolean
                      token:
                        type: string
        '400':
          description: Lỗi dữ liệu đầu vào
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/login:
    post:
      tags:
        - Auth
      summary: Đăng nhập
      description: Đăng nhập vào hệ thống
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Đăng nhập thành công!
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      fullName:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      emailVerified:
                        type: boolean
                      token:
                        type: string
        '400':
          description: Lỗi dữ liệu đầu vào
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Không có quyền truy cập
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/verify-email:
    post:
      tags:
        - Auth
        - OTP
      summary: Xác thực email
      description: Xác thực email sử dụng mã OTP gửi qua email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - otp
              properties:
                email:
                  type: string
                  format: email
                otp:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: Xác thực thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Xác nhận tài khoản thành công
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      fullName:
                        type: string
                      email:
                        type: string
                      emailVerified:
                        type: boolean
        '400':
          description: Mã không hợp lệ hoặc hết hạn
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/request-otp:
    post:
      tags:
        - Auth
        - OTP
      summary: Yêu cầu mã OTP
      description: Yêu cầu mã OTP cho xác thực email, đặt lại mật khẩu, hoặc đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - type
              properties:
                email:
                  type: string
                  format: email
                type:
                  type: string
                  enum: [email_verification, password_reset, login]
      responses:
        '200':
          description: Gửi mã OTP thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Mã OTP đã được gửi đến email của bạn
        '404':
          description: Không tìm thấy người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/verify-otp:
    post:
      tags:
        - Auth
        - OTP
      summary: Xác thực mã OTP
      description: Xác thực mã OTP đã nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - otp
                - type
              properties:
                userId:
                  type: string
                otp:
                  type: string
                  example: "123456"
                type:
                  type: string
                  enum: [email_verification, password_reset, login]
      responses:
        '200':
          description: Xác thực OTP thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Mã OTP không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Quên mật khẩu
      description: Yêu cầu đặt lại mật khẩu thông qua email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Gửi email đặt lại mật khẩu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Mã xác nhận đã được gửi đến email của bạn
        '404':
          description: Email không tồn tại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Đặt lại mật khẩu
      description: Đặt lại mật khẩu với mã OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - otp
                - newPassword
              properties:
                email:
                  type: string
                  format: email
                otp:
                  type: string
                newPassword:
                  type: string
                  format: password
                  minLength: 6
      responses:
        '200':
          description: Đặt lại mật khẩu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Đặt lại mật khẩu thành công
        '400':
          description: Mã xác nhận không hợp lệ hoặc đã hết hạn
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/check-email-verification:
    get:
      tags:
        - Auth
      summary: Kiểm tra trạng thái xác thực email
      description: Kiểm tra xem email của người dùng đã được xác thực chưa
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Trả về trạng thái xác thực email
          content:
            application/json:
              schema:
                type: object
                properties:
                  emailVerified:
                    type: boolean
                  email:
                    type: string
        '401':
          description: Chưa xác thực
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /users/profile:
    get:
      tags:
        - User
      summary: Lấy thông tin người dùng
      description: Lấy thông tin profile của người dùng đã đăng nhập
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          description: Chưa xác thực
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy thông tin người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /users/profile:
    put:
      tags:
        - User
      summary: Cập nhật thông tin người dùng
      description: Cập nhật thông tin profile của người dùng đã đăng nhập
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                phone:
                  type: string
                avatar:
                  type: string
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Cập nhật thành công!
                  data:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          description: Chưa xác thực
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /users/change-password:
    put:
      tags:
        - User
      summary: Đổi mật khẩu
      description: Đổi mật khẩu người dùng
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - currentPassword
                - newPassword
              properties:
                currentPassword:
                  type: string
                  format: password
                newPassword:
                  type: string
                  format: password
                  minLength: 6
      responses:
        '200':
          description: Đổi mật khẩu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Đổi mật khẩu thành công
        '400':
          description: Mật khẩu hiện tại không đúng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Chưa xác thực
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        fullName:
          type: string
        phone:
          type: string
        avatar:
          type: string
        role:
          type: string
          enum:
            - guest
            - customer
            - consultant
            - staff
            - manager
            - admin
        emailVerified:
          type: boolean
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    UserProfile:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        fullName:
          type: string
        phone:
          type: string
        avatar:
          type: string
        role:
          type: string
        emailVerified:
          type: boolean
        isActive:
          type: boolean
    
    OtpCode:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        type:
          type: string
          enum:
            - email_verification
            - password_reset
            - login
        otp:
          type: string
        expires:
          type: string
          format: date-time
        verified:
          type: boolean
        verifiedAt:
          type: string
          format: date-time
        attempts:
          type: integer
        createdAt:
          type: string
          format: date-time
    
    Error:
      type: object
      properties:
        message:
          type: string
